apiVersion: v1
kind: Pod
metadata:
  name: openstackcli
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: "kolla/centos-binary-openstack-base:2.0.2"
    command: ["/bin/bash","-c"]
    args: ["echo '. /srv/keystonerc-admin' >> ~/.bashrc; while true; do sleep 10000; done"]
    volumeMounts:
    - name: keystonerc-admin
      mountPath: /srv
  volumes:
  - name: keystonerc-admin
    secret:
      secretName: keystonerc-admin
